name: ci

on:
  push:
    branches:
      - main

jobs:
  test_endpoints:
    name: Test Endpoints
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create saloncito network
      run: |
        docker network create saloncito

    - name: Run setup script to start submodules' containers
      run: |
        chmod +x ./scripts/setup.sh
        ./scripts/setup.sh

    - name: Build and start nginx containers
      run: |
        docker compose -f ./.dockers/docker-compose.yml up --build -d

    - name: Wait for nginx to be ready
      run: |
        sleep 20

    - name: Run endpoint tests
      run: |
        chmod +x ./scripts/test_endpoints.sh
        ./scripts/test_endpoints.sh
