name: qa

on:
  push:
    branches:
      - main

jobs:
  setup_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Install make and npm
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        sudo apt-get install -y npm
        make --version  # Verifica la instalación de make
        npm --version   # Verifica la instalación de npm

    - name: Create saloncito network
      run: |
        docker network create saloncito

    - name: Run setup script to start submodules' containers
      run: |
        chmod +x ./scripts/setup.sh
        ./scripts/setup.sh

    - name: Build and start nginx containers
      run: |
        docker-compose -f ./dockers/docker-compose.yml up --build -d

    - name: Wait for nginx to be ready
      run: |
        sleep 20

    - name: Run endpoint tests
      run: |
        chmod +x ./scripts/test_endpoints.sh
        ./scripts/test_endpoints.sh
